import { Droplets, Flame, CheckCircle2Icon } from "lucide-react";

export const coffeeInventory = [
  {
    id: 0,
    name: "Yirgacheffe Gedeb",
    roaster: "Solar Flare Coffee",
    origin: "Ethiopia",
    countryCode: "ET",
    method: "Natural",
    roastLevel: 2,
    altitude: "2100",
    variety: "Heirloom",
    notes: ["Blueberry", "Earl Grey", "Lemon Zest"],
    intensity: { acidity: 5, body: 2, sweetness: 4 },
  },
  {
    id: 1,
    name: "Huila Reserva",
    roaster: "Mountain Peak Roasts",
    origin: "Colombia",
    countryCode: "CO",
    method: "Washed",
    roastLevel: 3,
    altitude: "1750",
    variety: "Caturra",
    notes: ["Caramel", "Red Apple", "Milk Chocolate"],
    intensity: { acidity: 3, body: 3, sweetness: 4 },
  },
  {
    id: 2,

    name: "Mandheling Gayo",
    roaster: "Deep Earth Beans",
    origin: "Indonesia",
    countryCode: "ID",
    method: "Giling Basah",
    roastLevel: 5,
    altitude: "1200",
    variety: "Typica",
    notes: ["Cedar", "Tobacco", "Dark Cocoa"],
    intensity: { acidity: 1, body: 5, sweetness: 2 },
  },
  {
    id: 3,
    name: "Nyeri Hill",
    roaster: "Velvet Drip",
    origin: "Kenya",
    countryCode: "KE",
    method: "Washed",
    roastLevel: 2,
    altitude: "1900",
    variety: "SL-28",
    notes: ["Blackcurrant", "Grapefruit", "Tomato"],
    intensity: { acidity: 5, body: 3, sweetness: 3 },
  },
  {
    id: 4,
    name: "Tarrazu Honey",
    roaster: "Golden Hour Roastery",
    origin: "Costa Rica",
    countryCode: "CR",
    method: "Honey",
    roastLevel: 3,
    altitude: "1500",
    variety: "Catuai",
    notes: ["Honey", "Molasses", "Stone Fruit"],
    intensity: { acidity: 2, body: 4, sweetness: 5 },
  },
  {
    id: 5,
    name: "Esmeralda Geisha",
    roaster: "Apex Roasts",
    origin: "Panama",
    countryCode: "PA",
    method: "Washed",
    roastLevel: 1,
    altitude: "1850",
    variety: "Geisha",
    notes: ["Jasmine", "Bergamot", "White Peach"],
    intensity: { acidity: 5, body: 1, sweetness: 5 },
  },
  {
    id: 6,
    name: "Antigua Pastoral",
    roaster: "Volcanica Beans",
    origin: "Guatemala",
    countryCode: "GT",
    method: "Washed",
    roastLevel: 3,
    altitude: "1650",
    variety: "Bourbon",
    notes: ["Milk Chocolate", "Brown Sugar", "Green Apple"],
    intensity: { acidity: 3, body: 3, sweetness: 4 },
  },
  {
    id: 7,
    name: "Dalat Bourbon",
    roaster: "Lotus Coffee Co.",
    origin: "Vietnam",
    countryCode: "VN",
    method: "Natural",
    roastLevel: 4,
    altitude: "1500",
    variety: "Catimor",
    notes: ["Dried Fig", "Roasted Peanut", "Dark Caramel"],
    intensity: { acidity: 2, body: 4, sweetness: 3 },
  },
  {
    id: 8,
    name: "Inzovu",
    roaster: "Thousand Hills",
    origin: "Rwanda",
    countryCode: "RW",
    method: "Fully Washed",
    roastLevel: 2,
    altitude: "1900",
    variety: "Red Bourbon",
    notes: ["Cranberry", "Orange Peel", "Black Tea"],
    intensity: { acidity: 4, body: 2, sweetness: 3 },
  },
  {
    id: 9,
    name: "Cajamarca Organic",
    roaster: "Andes Peak",
    origin: "Peru",
    countryCode: "PE",
    method: "Washed",
    roastLevel: 3,
    altitude: "1700",
    variety: "Caturra",
    notes: ["Toffee", "Red Currant", "Nougat"],
    intensity: { acidity: 3, body: 4, sweetness: 4 },
  },
];

export const grindHistory = [
  {
    id: 1,
    grindSetting: 18,
    date: "May 5, 2026",
    description: "Perfect balance, very sweet finish.",
    dose: 18,
    coffeeYield: 36,
    time: 26,
  },

  {
    id: 2,
    grindSetting: 20,
    date: "May 4, 2026",
    description: "A bit watery, need to go bit finer.",
    dose: 18,
    coffeeYield: 35,
    time: 15,
  },
  {
    id: 3,
    grindSetting: 25,
    date: "May 3, 2026",
    description: "Really watery and acidic, need to go a lot finer",
    dose: 18,
    coffeeYield: 38,
    time: 13,
  },
  {
    id: 4,
    grindSetting: 25,
    date: "May 3, 2026",
    description: "Really watery and acidic, need to go a lot finer",
    dose: 18,
    coffeeYield: 36,
    time: 10,
  },
];

export const TasteProfiles = [
  {
    id: "sour",
    label: "Sour / Acidic",
    description: "Sharp, vinegary, or salty notes",
    notes: ["Salty", "Sharp", "Thin/Watery", "Metallic"],
    icon: Droplets,
    sliderLabels: ["Sour", "Sweetly Acidic"],
  },
  {
    id: "balanced",
    label: "Sweet / Balanced",
    description: "Sweet, syrupy and rich",
    icon: CheckCircle2Icon,
    notes: ["Caramel", "Chocolate", "Fruity", "Velvety"],
    sliderLabels: ["OK", "Perfect"],
  },
  {
    id: "bitter",
    label: "Bitter / Harsh",
    description: "Dry, ashy, or burnt flavors",
    icon: Flame,
    notes: ["Ashy", "Dry/Astringent", "Tobacco", "Medicinal"],
    sliderLabels: ["Very Bitter", "Bitter Sweet"],
  },
];
